language: python

python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
  - 3.4

sudo: false

addons:
  apt_packages:
    - libbz2-dev
    - libhdf5-serial-dev
    - liblzo2-dev

install:
  - pip install cython
  - pip install .
  - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install unittest2; fi

script:
  - python -m tables.tests.test_all

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/58f8a9014ef02f6217ec
    on_success: change

