language: python

python:
  - 2.6
  - 2.7
  - "2.7_with_system_site_packages"
  - 3.2
  - "3.2_with_system_site_packages"
  - 3.3
  - 3.4

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libhdf5-serial-dev liblzo2-dev libbz2-dev python3-numpy
  - pip install -r requirements.txt --use-mirrors
  - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install -U unittest2 --use-mirrors; fi

script: make check
