language: python

virtualenv:
  system_site_packages: true

python:
  - "2.6"
  - "2.7"
  - "3.2"

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq libhdf5-serial-dev liblzo2-dev libbz2-dev python3-numpy
    - pip install -r requirements.txt --use-mirrors

script: "make check"

